#!/bin/bash

xecho () { if [[ "$v" -eq 1 ]]; then echo " + $@"; fi }

while getopts ":l:p:v" OPT; do
  case "$OPT" in
    l) lang="$OPTARG" ;;
    p) path="$OPTARG" ;;
    v) v=1 ;;
  esac
done

if ! [ -e "$path" ]; then
  path=`pwd`
fi

xecho "ass2srt ( lang = '$lang', path = '$path', verbose = '$v' )"

find "$path" -type f -name '*.mkv' | sort | while read file; do

  xecho "file = $file"

  filename="${file##*/}"
  if [ -z "$lang" ]; then
    basename="${filename%.*}"
  else
    basename="${filename%.*}.$lang"
  fi

  if [ -e "$basename.srt" ]; then
    xecho "Found $basename.srt"
    echo "Skipping $file"
    continue
  fi

  if [ -z "$lang" ]; then
    track=`mkvmerge -J "$file" | jq "first ( .tracks[]? | select ( .codec == \"SubStationAlpha\" ) .id )"`
  else
    track=`mkvmerge -J "$file" | jq "first ( .tracks[]? | select ( .codec == \"SubStationAlpha\" ) | select ( .properties.language == \"$lang\" ) .id )"`
  fi

  xecho "track = $track"

  if [ -z "$track" ]; then
    echo "Skipping $file"
    continue
  fi

  mkvextract tracks "$file" $track:"$basename.ass"
  ffmpeg -nostdin -hide_banner -i "$basename.ass" "$basename.srt"
  rm "$basename.ass"

done
