#!/bin/bash

xecho () { if [[ "$v" -eq 1 ]]; then echo "+ $*"; fi }

while getopts ":p:l:v" OPT; do
  case "$OPT" in
    p) path="$OPTARG" ;;
    l) lang="$OPTARG" ;;
    v) v=1 ;;
    *) echo "Usage: ass2srt [-p path] [-l language] [-v verbose]"; exit 1;;
  esac
done

if ! [ -e "$path" ]; then
  path=$(pwd)
fi

xecho "ass2srt [path='$path' language='$lang' verbose='$v']"

find "$(realpath -- "$path")" -type f -name '*.mkv' | sort | while read -r file; do

  xecho "Processing file '$file'"

  if [ -z "$lang" ]; then
    base="${file%.*}"
  else
    base="${file%.*}.$lang"
  fi

  if [ -e "$base.srt" ]; then
    xecho "Subtitles found, skipping"
    continue
  fi

  if [ -z "$lang" ]; then
    track=$(mkvmerge -J "$file" | jq "first ( .tracks[]? | select ( .codec == \"SubStationAlpha\" ) .id )")
  else
    track=$(mkvmerge -J "$file" | jq "first ( .tracks[]? | select ( .codec == \"SubStationAlpha\" ) | select ( .properties.language == \"$lang\" ) .id )")
  fi

  if [ -z "$track" ]; then
    xecho "No track found, skipping"
    continue
  fi

  mkvextract tracks "$file" "$track":"$base.ass"
  ffmpeg -nostdin -hide_banner -i "$base.ass" "$base.srt"
  rm "$base.ass"

done
