#!/bin/bash
# Convert subtitles from each MKV file in the given directory from .ass to .srt

# If no directory is given, work in local dir
if [ "$1" = "" ]; then
  dir="."
else
  dir="$1"
fi

# Get all the MKV files in this dir and its subdirs
find "$dir" -type f -name '*.mkv' | sort | while read filename
do
  # Get base name for subtitle
  basename=${filename%.*}

  # Skip processed files
  if [ -e "$basename.srt" ]; then
    echo "Skipping $filename"
    continue
  fi

  # If no tracknumber is given, find out which tracks contain the subtitles
  if [ "$2" = "" ]; then
    track=`mkvmerge -i "$filename" | grep 'subtitles' | head -1 | egrep -o "[0-9]{1,2}"`
  else
    track="$2"
  fi

  # Append lang tag to filename if given
  if [ "$3" = "" ]; then
    lang=""
  else
    lang=".$3"
  fi

  # Extract the track to a .ass file and convert to a .srt file
  echo "Processing $filename"
  mkvextract tracks "$filename" $track:"$basename.ass"
  ffmpeg -nostdin -hide_banner -i "$basename.ass" "$basename$lang.srt"
  rm "$basename.ass"
done
